version: '3'

tasks:

  gorun:
    desc: "Init Swagger and run the Go app"
    cmds:
      - cd cmd && swag init -d ./,../internal/ # TODO 需要把swag给跑通!
      - cd cmd && go run .

  gobuild:
    desc: "Init Swagger and build the Go binary"
    cmds:
      - cd cmd && swag init -d ./,../internal/
      - cd cmd && go build -o ../bin/gin-app-be .

  dockerbuild:
    desc: "Build Docker image"
    cmds:
      - docker build -t kizunaiix/my-web-demo-backend:latest .

  dockerrun-dev:
    desc: "Run Docker container with ENV=dev"
    cmds:
      - docker run -itd --name my-web-demo-backend -e ENV=dev -p 9000:9000 kizunaiix/my-web-demo-backend:latest

  # 可选：清理 Docker 容器
  docker-clean:
    desc: "Remove Docker container"
    cmds:
      - docker rm -f my-web-demo-backend || true
