version: "3"

tasks: # TODO 文件夹改名了需要全部重新写
  npm:build:
    desc: "Build React frontend"
    cmds:
      - cd frontend && npm install
      - cd frontend && npm run build

  swag:init:
    desc: "Initialize Swagger documentation"
    cmds:
      - cd backend/ && swag init -d cmd/,internal/

  go:run-dev:
    desc: "Init Swagger and run the Go app"
    env:
      ENV: dev
    deps:
      - swag:init
    cmds:
      - cd backend/work/ && go run ../cmd/

  go:run-prod:
    desc: "Init Swagger and run the Go app"
    env:
      ENV: prod
      GIN_MODE: release
    deps:
      - swag:init
    cmds:
      - cd backend/work/ && go run ../cmd/

  go:test:
    desc: "Run Go tests"
    deps:
      - swag:init
    cmds:
      - cd backend/ && go test ./...

  go:build:
    desc: "Init Swagger and build the Go binary"
    deps:
      - go:test
    cmds:
      - cd backend/cmd && go build -o ../bin/my-web-demo .

  docker:build:
    desc: "Build Docker image"
    env:
      VERSION: null # 可根据需要覆盖版本号
    deps:
      - npm:build
      - go:build
    cmds:
      # - cd backend/ && docker build -t kizunaiix/my-web-demo:${VERSION} . # 待验证
      - echo debug-v${VERSION}

  docker:run-dev:
    desc: "Run Docker container with ENV=dev"
    cmds:
      - docker run -itd \
        --name my-web-demo-dev \
        -e ENV=dev \
        -p 9000:9000 \
        kizunaiix/my-web-demo:latest

  docker:run-prod:
    desc: "Run Docker container with ENV=prod"
    cmds:
      - docker run -itd \
        --name prod-my-web-demo-prod \
        -e ENV=prod \
        -e GIN_MODE=release \
        -p 9000:9000 \
        kizunaiix/my-web-demo:latest

  # # 可选：清理 Docker 容器
  # docker:clean:
  #   desc: "Remove Docker container"
  #   cmds:
  #     - docker rm -f my-web-demo-backend || true
