basePath: /api
host: localhost:9000
info:
  contact: {}
  description: 这是一个基于 Gin 和 RPC 风格的习惯养成 API。
  title: 习惯养成 API 文档
  version: "0.1"
paths:
  /welcome:
    get:
      consumes:
      - '*/*'
      description: this api is like a "hello world"
      parameters:
      - description: 服务名称
        in: path
        name: service
        required: true
        type: string
      - description: 操作方法（create/update/delete）
        in: query
        name: method
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: 成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 服务不存在
          schema:
            additionalProperties: true
            type: object
      summary: welcome api
      tags:
      - RPC-like
swagger: "2.0"
