basePath: /api
host: localhost:9000
info:
  contact: {}
  description: 这是一个基于 Gin 和 RPC 风格的习惯养成 API。
  title: 习惯养成 API 文档
  version: "1.0"
paths:
  /api:
    get:
      consumes:
      - application/json
      description: 通过 `method` 参数区分创建、更新、删除等操作
      parameters:
      - description: 服务名称
        in: path
        name: service
        required: true
        type: string
      - description: 操作方法（create/update/delete）
        in: query
        name: method
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 服务不存在
          schema:
            additionalProperties: true
            type: object
      summary: 处理 RPC 风格 API
      tags:
      - RPC
swagger: "2.0"
